# Generated by Django 6.0.2 on 2026-06-27 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('emoji', models.CharField(default='📞', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
                ('audience', models.CharField(choices=[('driver', 'Drivers'), ('rider', 'Riders'), ('pedestrian', 'Pedestrians')], default='driver', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Rules'), ('highway', 'Highway Rules'), ('pedestrian', 'Pedestrian Rules'), ('cyclist', 'Cyclist Rules')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sign_type', models.CharField(choices=[('mandatory', 'Mandatory Signs'), ('cautionary', 'Cautionary Signs'), ('informatory', 'Informatory Signs')], default='mandatory', max_length=50)),
                ('emoji', models.CharField(default='🚦', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HazardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('hazard_type', models.CharField(choices=[('pothole', 'Pothole'), ('accident', 'Accident'), ('flooding', 'Road Flooding'), ('construction', 'Road Construction'), ('signal', 'Broken Signal'), ('other', 'Other')], default='other', max_length=50)),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
